# -*- coding: utf-8 -*-
"""ixtiyoriy-dastur.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTaqMx8fDC3S0OgJ5wWeU0s4tmhgvN6V
"""

import random

secret_number = random.randint(1, 100)
guesses_left = 7

print("Raqamni top o'yiniga xush kelibsiz!")
print("1 dan 100 gacha raqam o'ylayman.")

while guesses_left > 0:
    print(f"\nSizda {guesses_left} urinish qoldi.")
    try:
        guess = int(input("Javob: "))
    except ValueError:
        print("Boshqa raqam kiriting.")
        continue

    if guess < secret_number:
        print("O'ylangan raqamdan kichik!")
    elif guess > secret_number:
        print("O'ylangan raqamdan katta!")
    else:
        print(f"\nTabriklayman! Siz o'ylangan raqamni {7 - guesses_left} urinishda topdingiz!")
        break

    guesses_left -= 1

if guesses_left == 0:
    print(f"\nUrinishlaringiz tugadi. O'ylangan raqam: {secret_number}.")